import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [ItemSelected, setItemSelected] = useState(1);
  return (
    <div>
      <Head>
        <title>Assembly AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center items-center gap-2 mt-40">
          {[1, 2, 3, 4].map((mynumber) => {
            return (
              <div
                key={mynumber}
                onClick={() => setItemSelected(mynumber)}
                className={`h-2 w-2 rounded-full cursor-pointer ${
                  mynumber === ItemSelected ? "bg-[#91939d]" : "bg-[#dee2e6]"
                }`}
              />
            );
          })}
        </div>
        <br />
        <div className="flex justify-center items-center mt-2 ml-40 mr-40">
          <div className="h-5 w-5 p-5 border border-[#dee2e6] rop-shadow-md rounded-full relative cursor-pointer">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-6 h-6"
              style={{
                position: "absolute",
                top: "50%",
                transform: "translate(-50%, -50%)",
              }}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15.75 19.5L8.25 12l7.5-7.5"
              />
            </svg>
          </div>
          <div className="hidden sm:flex w-full bg-indigo-400 h-0.5 "></div>
          <div
            onClick={() => setItemSelected(1)}
            className="h-20 w-20 p-10 border border-indigo-400 rounded-full relative cursor-pointer"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-12 h-12"
              style={{
                position: "absolute",
                top: "50%",
                transform: "translate(-50%, -50%)",
              }}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M8.25 3v1.5M4.5 8.25H3m18 0h-1.5M4.5 12H3m18 0h-1.5m-15 3.75H3m18 0h-1.5M8.25 19.5V21M12 3v1.5m0 15V21m3.75-18v1.5m0 15V21m-9-1.5h10.5a2.25 2.25 0 002.25-2.25V6.75a2.25 2.25 0 00-2.25-2.25H6.75A2.25 2.25 0 004.5 6.75v10.5a2.25 2.25 0 002.25 2.25zm.75-12h9v9h-9v-9z"
              />
            </svg>
          </div>
          <div className="hidden sm:flex w-full bg-indigo-400 h-0.5 "></div>
          <div
            className={`hidden sm:flex w-full ${
              ItemSelected > 1 ? "bg-indigo-400" : "bg-gray-200"
            } 0 h-0.5`}
          ></div>
          <div
            onClick={() => setItemSelected(2)}
            className={`h-20 w-20 p-10 border ${
              ItemSelected >= 2 ? "border-indigo-400" : "border-[#dee2e6]"
            }  rounded-full relative cursor-pointer`}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-12 h-12"
              style={{
                position: "absolute",
                top: "50%",
                transform: "translate(-50%, -50%)",
              }}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15.59 14.37a6 6 0 01-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 006.16-12.12A14.98 14.98 0 009.631 8.41m5.96 5.96a14.926 14.926 0 01-5.841 2.58m-.119-8.54a6 6 0 00-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 00-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 01-2.448-2.448 14.9 14.9 0 01.06-.312m-2.24 2.39a4.493 4.493 0 00-1.757 4.306 4.493 4.493 0 004.306-1.758M16.5 9a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z"
              />
            </svg>
          </div>
          <div
            className={`hidden sm:flex w-full ${
              ItemSelected > 1 ? "bg-indigo-400" : "bg-gray-200"
            } 0 h-0.5`}
          ></div>
          <div
            className={`hidden sm:flex w-full ${
              ItemSelected > 2 ? "bg-indigo-400" : "bg-gray-200"
            } 0 h-0.5`}
          ></div>{" "}
          <div
            onClick={() => setItemSelected(3)}
            className={`h-20 w-20 p-10 border ${
              ItemSelected >= 3 ? "border-indigo-400" : "border-[#dee2e6]"
            }  rounded-full relative cursor-pointer`}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-12 h-12"
              style={{
                position: "absolute",
                top: "50%",
                transform: "translate(-50%, -50%)",
              }}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M2.25 15a4.5 4.5 0 004.5 4.5H18a3.75 3.75 0 001.332-7.257 3 3 0 00-3.758-3.848 5.25 5.25 0 00-10.233 2.33A4.502 4.502 0 002.25 15z"
              />
            </svg>
          </div>
          <div
            className={`hidden sm:flex w-full ${
              ItemSelected > 2 ? "bg-indigo-400" : "bg-gray-200"
            } 0 h-0.5`}
          ></div>{" "}
          <div
            className={`hidden sm:flex w-full ${
              ItemSelected > 3 ? "bg-indigo-400" : "bg-gray-200"
            } 0 h-0.5`}
          ></div>{" "}
          <div
            onClick={() => setItemSelected(4)}
            className={`h-20 w-20 p-10 border ${
              ItemSelected >= 4 ? "border-indigo-400" : "border-[#dee2e6]"
            }  rounded-full relative cursor-pointer`}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-12 h-12"
              style={{
                position: "absolute",
                top: "50%",
                transform: "translate(-50%, -50%)",
              }}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
              />
            </svg>
          </div>
          <div
            className={`hidden sm:flex w-full ${
              ItemSelected > 3 ? "bg-indigo-400" : "bg-gray-200"
            } 0 h-0.5`}
          ></div>
          <div className="h-5 w-5 p-5 border border-[#dee2e6] rop-shadow-md rounded-full relative cursor-pointer">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-6 h-6"
              style={{
                position: "absolute",
                top: "50%",
                transform: "translate(-50%, -50%)",
              }}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M8.25 4.5l7.5 7.5-7.5 7.5"
              />
            </svg>
          </div>
        </div>

        {/* ITEM 1 */}

        {ItemSelected === 1 && (
          <div>
            <div className="text-center mt-40 animated repeat-1 bounceIn">
              <h2 className="font-semibold text-3xl">AI for Humans</h2>
            </div>
            <div className="flex justify-center items-center">
              <p className="text-xl mt-2 animated repeat-1 bounceIn w-[45rem] text-center">
                Web application to detect cancer through Artificial
                Intelligence, simply upload a real image of the person and get
                the results
              </p>
            </div>

            <div className="flex justify-center items-center">
              <button
                id="next"
                onClick={() => setItemSelected(2)}
                className="animated repeat-1 bounceIn select-none text-lg hover:shadow-md bg-[#4361ee] hover:bg-black text-white focus:outline-none font-medium rounded-lg inline-flex items-center px-5 py-2.5 mb-2 mt-2 border border-transparent"
              >
                See how to works
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="ml-2 -mr-1 w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M8.25 4.5l7.5 7.5-7.5 7.5"
                  />
                </svg>
              </button>
            </div>
          </div>
        )}

        {ItemSelected === 2 && (
          <div>
            <div className="text-center mt-40 backInUp repeat-1 bounceIn">
              <h2 className="font-semibold text-3xl">Fast Detection</h2>
            </div>
            <div className="flex justify-center items-center">
              <p className="text-xl mt-2 animated repeat-1 backInUp w-[45rem] text-center">
                Web application optimized to detect the disease through real
                images of the person.
              </p>
            </div>

            <div className="flex justify-center items-center">
              <button
                id="next"
                onClick={() => setItemSelected(3)}
                className="animated repeat-1 backInUp select-none text-lg hover:shadow-md bg-[#4361ee] hover:bg-black text-white focus:outline-none font-medium rounded-lg inline-flex items-center px-5 py-2.5 mb-2 mt-2 border border-transparent"
              >
                Cloud native application
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="ml-2 -mr-1 w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M8.25 4.5l7.5 7.5-7.5 7.5"
                  />
                </svg>
              </button>
            </div>
          </div>
        )}

        {ItemSelected === 4 && (
          <div className="grid grid-cols-2">
            <div>
              <div className="text-center mt-40 flipInX repeat-1 bounceIn">
                <h2 className="font-semibold text-3xl">Analytics</h2>
              </div>
              <div className="flex justify-center items-center">
                <p className="text-xl mt-2 flipInX repeat-1 bounceIn w-[45rem] text-center">
                  Get training analytics and test results, remember that we save
                  this information so you can export it
                </p>
              </div>

              <div className="flex justify-center items-center">
                <button
                  id="next"
                  className="animated repeat-1 flipInX select-none text-lg hover:shadow-md bg-[#4361ee] hover:bg-black text-white focus:outline-none font-medium rounded-lg inline-flex items-center px-5 py-2.5 mb-2 mt-2 border border-transparent"
                >
                  Get started
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="ml-2 -mr-1 w-6 h-6"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M8.25 4.5l7.5 7.5-7.5 7.5"
                    />
                  </svg>
                </button>
              </div>
            </div>

            <div className="animated repeat-1 flipInX mt-20">
              <svg
                width="558"
                height="470"
                viewBox="0 0 658 570"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M381.612 238.725H0V0H381.612V238.725Z" fill="white" />
                <path
                  d="M381.612 238.725H0V0H381.612V238.725ZM1.74252 236.983H379.869V1.74252H1.74252V236.983Z"
                  fill="#3F3D56"
                />
                <path
                  d="M334.999 569.369H117.184V330.643H334.999V569.369Z"
                  fill="white"
                />
                <path
                  d="M334.999 569.369H117.184V330.643H334.999V569.369ZM118.927 567.626H333.257V332.386H118.927V567.626Z"
                  fill="#3F3D56"
                />
                <path
                  d="M226.092 373.335V392.503C237.465 392.503 248.583 395.875 258.039 402.194C267.495 408.512 274.866 417.493 279.218 428C283.57 438.508 284.709 450.07 282.49 461.224C280.271 472.379 274.795 482.625 266.753 490.667L280.306 504.22C291.029 493.498 298.331 479.836 301.29 464.964C304.248 450.091 302.73 434.675 296.927 420.665C291.124 406.655 281.296 394.681 268.688 386.256C256.08 377.832 241.256 373.335 226.092 373.335Z"
                  fill="#E6E6E6"
                />
                <path
                  d="M280.306 504.22L266.753 490.667C256.922 500.5 243.86 506.437 229.987 507.377C216.114 508.318 202.37 504.199 191.302 495.782L179.7 511.048C194.461 522.266 212.786 527.756 231.284 526.501C249.781 525.246 267.197 517.33 280.306 504.22Z"
                  fill="#575A89"
                />
                <path
                  d="M168.589 450.006C168.589 442.454 170.076 434.977 172.966 428C175.856 421.024 180.091 414.685 185.431 409.345C190.771 404.005 197.11 399.77 204.086 396.88C211.063 393.99 218.54 392.503 226.092 392.503V373.335C210.042 373.335 194.396 378.372 181.361 387.736C168.325 397.099 158.557 410.318 153.433 425.529C148.309 440.739 148.088 457.174 152.8 472.516C157.513 487.859 166.922 501.336 179.7 511.048L191.302 495.782C184.238 490.425 178.511 483.503 174.57 475.561C170.63 467.619 168.582 458.872 168.589 450.006V450.006Z"
                  fill="#4362EE"
                />
                <path
                  d="M657.365 421.255H439.551V182.529H657.365V421.255Z"
                  fill="white"
                />
                <path
                  d="M657.365 421.255H439.551V182.529H657.365V421.255ZM441.293 419.512H655.623V184.271H441.293V419.512Z"
                  fill="#3F3D56"
                />
                <path
                  d="M510.123 328.465H470.916V391.196H510.123V328.465Z"
                  fill="#575A89"
                />
                <path
                  d="M566.754 285.773H527.548V391.196H566.754V285.773Z"
                  fill="#E6E6E6"
                />
                <path
                  d="M623.386 236.112H584.18V391.196H623.386V236.112Z"
                  fill="#4362EE"
                />
                <path
                  d="M636.455 392.939H460.461V210.845H462.203V391.196H636.455V392.939Z"
                  fill="#3F3D56"
                />
                <path
                  d="M328.615 188.799H52.9968C52.768 188.799 52.5486 188.708 52.3869 188.546C52.2251 188.384 52.1342 188.165 52.1342 187.936V55.8322C52.1342 55.6035 52.2251 55.3841 52.3868 55.2223C52.5486 55.0605 52.768 54.9697 52.9968 54.9697C53.2255 54.9697 53.4449 55.0605 53.6067 55.2223C53.7685 55.3841 53.8593 55.6035 53.8593 55.8322V187.073H328.615C328.729 187.073 328.841 187.095 328.946 187.138C329.051 187.181 329.146 187.245 329.227 187.325C329.307 187.405 329.371 187.5 329.415 187.605C329.458 187.71 329.48 187.823 329.48 187.936C329.48 188.05 329.458 188.162 329.415 188.267C329.371 188.372 329.307 188.467 329.227 188.547C329.146 188.627 329.051 188.691 328.946 188.734C328.841 188.777 328.729 188.799 328.615 188.799V188.799Z"
                  fill="#3F3D56"
                />
                <path
                  d="M111.884 179.31H86.8158C86.137 179.31 85.4862 179.04 85.0062 178.56C84.5261 178.08 84.2561 177.429 84.2553 176.75V142.193C84.2561 141.514 84.5261 140.863 85.0062 140.383C85.4862 139.903 86.137 139.633 86.8158 139.633H111.884C112.563 139.633 113.214 139.903 113.694 140.383C114.174 140.863 114.444 141.514 114.445 142.193V176.75C114.444 177.429 114.174 178.08 113.694 178.56C113.214 179.04 112.563 179.31 111.884 179.31V179.31Z"
                  fill="#4362EE"
                />
                <path
                  d="M157.6 179.31H132.531C131.853 179.31 131.202 179.04 130.722 178.56C130.242 178.08 129.972 177.429 129.971 176.75V109.416C129.972 108.737 130.242 108.086 130.722 107.606C131.202 107.126 131.853 106.856 132.531 106.855H157.6C158.279 106.856 158.93 107.126 159.41 107.606C159.89 108.086 160.16 108.737 160.161 109.416V176.75C160.16 177.429 159.89 178.08 159.41 178.56C158.93 179.04 158.279 179.31 157.6 179.31V179.31Z"
                  fill="#4362EE"
                />
                <path
                  d="M203.316 179.31H178.247C177.568 179.31 176.917 179.04 176.437 178.56C175.957 178.08 175.687 177.429 175.687 176.75V142.193C175.687 141.514 175.957 140.863 176.437 140.383C176.917 139.903 177.568 139.633 178.247 139.633H203.316C203.994 139.633 204.645 139.903 205.125 140.383C205.605 140.863 205.875 141.514 205.876 142.193V176.75C205.875 177.429 205.605 178.08 205.125 178.56C204.645 179.04 203.994 179.31 203.316 179.31V179.31Z"
                  fill="#4362EE"
                />
                <path
                  d="M249.031 179.31H223.963C223.299 179.325 222.657 179.075 222.177 178.617C221.698 178.159 221.419 177.529 221.402 176.866V96.3614C221.419 95.6981 221.698 95.0684 222.177 94.6102C222.657 94.1521 223.299 93.9028 223.963 93.9171H249.031C249.695 93.9028 250.337 94.1521 250.817 94.6102C251.296 95.0684 251.575 95.6981 251.592 96.3614V176.866C251.575 177.529 251.296 178.159 250.817 178.617C250.337 179.075 249.695 179.325 249.031 179.31V179.31Z"
                  fill="#4362EE"
                />
                <path
                  d="M294.747 179.31H269.678C269 179.31 268.349 179.04 267.869 178.56C267.389 178.08 267.119 177.429 267.118 176.75V73.1883C267.119 72.5095 267.389 71.8587 267.869 71.3787C268.349 70.8987 269 70.6287 269.678 70.628H294.747C295.426 70.6287 296.077 70.8987 296.557 71.3787C297.037 71.8587 297.307 72.5095 297.307 73.1883V176.75C297.307 177.429 297.037 178.08 296.557 178.56C296.077 179.04 295.426 179.31 294.747 179.31V179.31Z"
                  fill="#4362EE"
                />
                <path
                  d="M99.3501 129.282C102.208 129.282 104.525 126.965 104.525 124.107C104.525 121.248 102.208 118.931 99.3501 118.931C96.4918 118.931 94.1747 121.248 94.1747 124.107C94.1747 126.965 96.4918 129.282 99.3501 129.282Z"
                  fill="#3F3D56"
                />
                <path
                  d="M145.066 95.6422C147.924 95.6422 150.241 93.3251 150.241 90.4669C150.241 87.6086 147.924 85.2915 145.066 85.2915C142.207 85.2915 139.89 87.6086 139.89 90.4669C139.89 93.3251 142.207 95.6422 145.066 95.6422Z"
                  fill="#3F3D56"
                />
                <path
                  d="M190.781 129.282C193.64 129.282 195.957 126.965 195.957 124.107C195.957 121.248 193.64 118.931 190.781 118.931C187.923 118.931 185.606 121.248 185.606 124.107C185.606 126.965 187.923 129.282 190.781 129.282Z"
                  fill="#3F3D56"
                />
                <path
                  d="M236.497 79.2536C239.355 79.2536 241.672 76.9365 241.672 74.0782C241.672 71.2199 239.355 68.9029 236.497 68.9029C233.639 68.9029 231.322 71.2199 231.322 74.0782C231.322 76.9365 233.639 79.2536 236.497 79.2536Z"
                  fill="#3F3D56"
                />
                <path
                  d="M282.213 60.2773C285.071 60.2773 287.388 57.9602 287.388 55.1019C287.388 52.2436 285.071 49.9265 282.213 49.9265C279.354 49.9265 277.037 52.2436 277.037 55.1019C277.037 57.9602 279.354 60.2773 282.213 60.2773Z"
                  fill="#3F3D56"
                />
                <path
                  d="M190.89 125.266L145.066 90.943L99.867 124.797L98.833 123.416L145.066 88.787L190.672 122.947L235.993 73.352L236.175 73.278L281.89 54.858L282.535 56.459L237.001 74.805L190.89 125.266Z"
                  fill="#3F3D56"
                />
              </svg>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
